// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Comment struct {
	ID        int32         `json:"id"`
	PostID    sql.NullInt32 `json:"post_id"`
	UserID    sql.NullInt32 `json:"user_id"`
	Content   string        `json:"content"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Image struct {
	ID         int32          `json:"id"`
	UserID     sql.NullInt32  `json:"user_id"`
	FilePath   string         `json:"file_path"`
	AltText    sql.NullString `json:"alt_text"`
	UploadedAt sql.NullTime   `json:"uploaded_at"`
}

type Post struct {
	ID        int32          `json:"id"`
	UserID    sql.NullInt32  `json:"user_id"`
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	Type      string         `json:"type"`
	Status    sql.NullString `json:"status"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type PostImage struct {
	PostID       int32         `json:"post_id"`
	ImageID      int32         `json:"image_id"`
	DisplayOrder sql.NullInt32 `json:"display_order"`
}

type PostTag struct {
	PostID int32 `json:"post_id"`
	TagID  int32 `json:"tag_id"`
}

type Tag struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID           int32          `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	Bio          sql.NullString `json:"bio"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
